# Generated by Django 4.1.6 on 2023-02-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('salary', models.IntegerField()),
                ('managerId', models.IntegerField()),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_operation.department')),
            ],
        ),
    ]
